### ISSUE TITLE
Feature: User can view cards

### ISSUE THREAD

**Issue by shawnkost** [shawnkost/lorcana-collection#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view all cards that currently exist in the game

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

A user should be able to visit the webpage and view all of the cards that currently exist in the game

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="701" alt="Screenshot 2023-12-05 at 9 42 46 AM" src="https://github.com/shawnkost/lorcana-collection/assets/71413368/e023c421-99d1-448c-bd7c-8ce76468097d">

## ✅ Task Lists

> ##### Commit checklists for tasks needed to complete the feature.

### 🐘 Database Tasks

- [ ] Seed database with current card data in game

### ☁️ Server Tasks

- [ ] Test endpoint with HTTPie
- [ ] Create utility function to make a request to grab card data
- [ ] Handle all errors and respond to the client

### ⚡ Client Tasks

- [ ] Create a NavBar component to match wireframes
  - [ ] Add click event to hamburger menu to show mobile menu items
  - [ ] Add click event to mobile menu items with no functionality for now
- [ ] Create landing page to match wireframes
  - [ ] Add click event to "View Cards" button to redirect to card view
- [ ] Create page for card view
  - [ ] Add search bar and filters button with no functionality for now
  - [ ] Add logos for various inks that will be used as filters later on
  - [ ] Map over the cards returned from database, and generate DOM tree for them

### 🧑‍⚕️ Clean Up Tasks

- [ ] Make sure that no React state objects are being mutated.
- [ ] Make sure that no event listeners are manipulating the DOM directly.
- [ ] Make sure that click targets are either `<a>` or `<button>` elements.
- [ ] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [ ] Remove all console logs.
- [ ] Remove all commented out code.
- [ ] Remove all CSS properties that have no effect.
- [ ] Check all code for proper formatting and indentation.
- [ ] Confirm that there are no errors in the console while using the application.
- [ ] Confirm that all previous functionality still works without errors.
- [ ] Confirm that the user interface looks natural on both mobile and desktop screens.
